apiVersion: v1
kind: Service
metadata:
  labels:
    app: boot-spring
  name: boot-spring
  namespace: default
spec:  
  ports:
  - nodePort: 30093
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: boot-spring
  type: NodePort
